# GenAI

Recent: 

- [Amy Webb SxSW 2025 - Emerging Tech Trend](https://www.youtube.com/watch?v=oT33_MrqyHo)

## What is GenAI?

- Why not ask [perplexity.ai](https://www.perplexity.ai/) ?
- Or [duck.ai](https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1)?

## GPT - Generative Pre-Trained Transformer

- [Generative AI & the Transformer (Financial Times, interactive site)](https://ig.ft.com/generative-ai/)
- [History of ChatGPT (30 min)](https://www.youtube.com/watch?v=OFS90-FX6pg)
- [But what is a GPT? (3Blue1Brown, 30 min)](https://www.youtube.com/watch?v=wjZofJX0v4M)

## Prompting

... and some sources with tips how to prompt every day... 

- [Prompting basics](https://www.promptingguide.ai/introduction/basics)
- [Prompting ChatGPT4.1](https://x.com/gregisenberg/status/1912298263987757296?s=48)
- [Look for course with 'Prompting' in name: https://www.deeplearning.ai/short-courses/](https://www.deeplearning.ai/short-courses/)
- [Ruben Hassid: RISE](https://www.linkedin.com/posts/ruben-hassid_your-prompts-are-too-vague-heres-a-simple-activity-7336980233977286657-4RBY)

- [mention of Llama Prompt Optimization](https://learn.deeplearning.ai/courses/building-with-llama-4)

## Hallucinating 

When nonsense comes out of an LLM (or out of a Human by the way)
we call it hallucination. Some questions can trigger hallucination. 

###

### 'Which day do I have to put the garbage can out on the street?' 

Some LLMs will give you a Date when you ask for one, a percentage when
you ask for one, even when the LLM could not possibly give an answer
to your question. If you ask which day you should put my garbage out and 
the LLM mentions a Date without having a clue where you are then you can be 
sure it just made up a Date (because you asked for a Date). 

### 'Can you help me find my lost keys?'


### 'Can you create an image of a watch that says it is 3 o' clock?'

Try it. You will find that a picture of a clock often shows 10:10. 
You could ask [perplexity.ai](https://perplexity.ai): 
Why does a generated image of a clock point to 10:10?


## RAG - Retrieval Augmented Generation

- [IBM, Marina Danilevsky (7 min)](https://www.youtube.com/watch?v=T-D1OfcDW1M)
- [https://www.deeplearning.ai/short-courses: Great resource for courses!](https://www.deeplearning.ai/short-courses/)

## Active Inference

- [Andy Clark about Active Interference: How the Brains shapes reality (60 min)](https://www.youtube.com/watch?v=A1Ghrd7NBtk)

## Running LLM's locally

On your laptop/desktop or on a company server: 

- [ollama](https://ollama.com/)
- [LM-studio](https://lmstudio.ai/)
- [Open Web AI](https://docs.openwebui.com/)

## Coding with GenAI

- [cursor course: AI Fundamentals](https://cursor.com/learn)
- [vs code with co-pilot (free plan)](https://code.visualstudio.com/docs/copilot/overview)
- [Cursor.com (20 euro p/m)](https://cursor.com)
- [AIDER.chat (free)](https://aider.chat/)
- [Open Devin: Create any Application with Open Source AI Engineer](https://www.youtube.com/watch?v=3-q5GzRNEe0)
- [Avante (AI in neovim, free)](https://nithinbekal.com/posts/avante-nvim/)

## MCP - Model Context Protocol

A way (AI) systems can communicate to each other. 
This way it helps building modular (AI) systems.  

- [MCP Quickstart](https://modelcontextprotocol.info/docs/quickstart/quickstart/)
- [Short deeplearning.ai course MCP](https://learn.deeplearning.ai/courses/mcp-build-rich-context-ai-apps-with-anthropic/lesson/fkbhh/introduction)

## GenAI

- [awesome GenAI guide](https://github.com/aishwaryanr/awesome-generative-ai-guide)
- [huggingface](https://huggingface.co/)

## Some more sites, nice to play around with

- [https://skyreels.ai/](https://skyreels.ai/)
- [https://civitai.com/](https://civitai.com/)
