Class {
	#name : #WASlidesGeneticAlgo,
	#superclass : #WorkshopAI,
	#category : #'NeuralNetwork-GToolkit'
}

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0540: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0540
		  fromPicture: '2021-AI-General.054.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0550: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0550
		  fromPicture: '2021-AI-General.055.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0560: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0560
		  fromPicture: '2021-AI-General.056.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0570: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0570
		  fromPicture: '2021-AI-General.057.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0580: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0580
		  fromPicture: '2021-AI-General.058.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0590: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0590
		  fromPicture: '2021-AI-General.059.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0600: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0600
		  fromPicture: '2021-AI-General.060.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0610: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0610
		  fromPicture: '2021-AI-General.061.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0620: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0620
		  fromPicture: '2021-AI-General.062.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0630: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0630
		  fromPicture: '2021-AI-General.063.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0640: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0640
		  fromPicture: '2021-AI-General.064.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0650: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0650
		  fromPicture: '2021-AI-General.065.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0660: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0660
		  fromPicture: '2021-AI-General.066.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0670: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0670
		  fromPicture: '2021-AI-General.067.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0680: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0680
		  fromPicture: '2021-AI-General.068.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0690: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0690
		  fromPicture: '2021-AI-General.069.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0700: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0700
		  fromPicture: '2021-AI-General.070.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0710: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0710
		  fromPicture: '2021-AI-General.071.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0720: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0720
		  fromPicture: '2021-AI-General.072.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0730: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0730
		  fromPicture: '2021-AI-General.073.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0740: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0740
		  fromPicture: '2021-AI-General.074.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0750: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0750
		  fromPicture: '2021-AI-General.075.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0760: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0760
		  fromPicture: '2021-AI-General.076.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0770: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0770
		  fromPicture: '2021-AI-General.077.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0780: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0780
		  fromPicture: '2021-AI-General.078.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0790: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0790
		  fromPicture: '2021-AI-General.079.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0800: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0800
		  fromPicture: '2021-AI-General.080.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0810: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0810
		  fromPicture: '2021-AI-General.081.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0820: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0820
		  fromPicture: '2021-AI-General.082.png'
]

{ #category : #slides }
WASlidesGeneticAlgo >> slidePercep0830: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0830
		  fromPicture: '2021-AI-General.083.png'
]
