Class {
	#name : #WASlidesFinal,
	#superclass : #WorkshopAI,
	#category : #'NeuralNetwork-GToolkit'
}

{ #category : #slides }
WASlidesFinal >> slidePercep0980: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0980
		  fromPicture: '2021-AI-General.098.png'
]

{ #category : #slides }
WASlidesFinal >> slidePercep0990: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.0990
		  fromPicture: '2021-AI-General.099.png'
]

{ #category : #slides }
WASlidesFinal >> slidePercep1000: aSlide [

	<gtSlide>
	^ self
		  slide: aSlide
		  prio: 1.1000
		  fromPicture: '2021-AI-General.1000.png'
]
