---
title: "OK-Next"
---

Title: OK, now what could I do next?
#OK, now what could I do next?

By now you have seen a bit of the idea behind Artificial Neural Networks. Maybe you're appetite if satisfied and you know what you want to know. Maybe you want to dive in the Mathematics behind it. Maybe you want to get hands-on in some programming language.
The scripts in this workshop come from the excellent book 'Agile AI in Pharo' by Alexandre Bergel. In the video 'Introduction to neural networks, genetic, and neuroevolution'  Alexandre Bergel himself tells the story using Pharo, so there you can find a lot of information: 
[video 'Introduction to neural networks, genetic, and neuroevolution'](https://tube.switch.ch/videos/v6uqRi7Lfm)). After Neural Networks he talks about Genetic Algorithms and in the end about Neuroevolution using NEAT.
Or you could follow a tutorial in (for example) Python, Keras, Tensorflow...
[Coding Lane: Image Classification using CNN in Keras](https://www.youtube.com/watch?v=J1jhfAw5Uvo)
[InvesTime: Deep-learning in Health care](https://www.youtube.com/watch?v=Fxy6WTnUIww)
[3Blue1Brown - But what is a convolution?](https://www.youtube.com/watch?v=KuXjwB4LzSA)

