Class {
	#name : #NeuralNetworkTutorial,
	#superclass : #AbstractTutorial,
	#category : #NeuralTutorial
}

{ #category : #tutorial }
NeuralNetworkTutorial >> tutorial [ 
	"ProfStef goOn: NeuralNetworkTutorial "
	^ #( welcome welcome2 welcome3 ) 
]

{ #category : #lessons }
NeuralNetworkTutorial >> welcome [
^ Lesson
title: 'Welcome' 
lesson: 
'"Hello! This is an introduction in Neural Networks. 

We start by looking at a Perceptron "

ProfStef next.'
]

{ #category : #lessons }
NeuralNetworkTutorial >> welcome2 [
^ Lesson
title: 'Welcome2' 
lesson: 
'"Hello! This is an introduction in Neural Networks. 

We start by looking at a Perceptron "

ProfStef next.'
]

{ #category : #lessons }
NeuralNetworkTutorial >> welcome3 [
^ Lesson
title: 'Welcome3' 
lesson: 
'"Hello! This is an introduction in Neural Networks. 

We start by looking at a Perceptron "

ProfStef next.'
]
